//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPCamaraComercio.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LogError
    {
        public int IDError { get; set; }
        public string NameClass { get; set; }
        public string NameMethod { get; set; }
        public string Message { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IDCorresponsal { get; set; }
    }
}
