//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPCamaraComercio.WCFCamaraComercio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tipo_busqueda", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    public enum tipo_busqueda : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nombre = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nit = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaConsulta", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class RespuestaConsulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPCamaraComercio.WCFCamaraComercio.Response responseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPCamaraComercio.WCFCamaraComercio.Response response {
            get {
                return this.responseField;
            }
            set {
                if ((object.ReferenceEquals(this.responseField, value) != true)) {
                    this.responseField = value;
                    this.RaisePropertyChanged("response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int registrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPCamaraComercio.WCFCamaraComercio.Resultado[] resultadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string frid {
            get {
                return this.fridField;
            }
            set {
                if ((object.ReferenceEquals(this.fridField, value) != true)) {
                    this.fridField = value;
                    this.RaisePropertyChanged("frid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lrid {
            get {
                return this.lridField;
            }
            set {
                if ((object.ReferenceEquals(this.lridField, value) != true)) {
                    this.lridField = value;
                    this.RaisePropertyChanged("lrid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int registros {
            get {
                return this.registrosField;
            }
            set {
                if ((this.registrosField.Equals(value) != true)) {
                    this.registrosField = value;
                    this.RaisePropertyChanged("registros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPCamaraComercio.WCFCamaraComercio.Resultado[] resultados {
            get {
                return this.resultadosField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadosField, value) != true)) {
                    this.resultadosField = value;
                    this.RaisePropertyChanged("resultados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultado", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class Resultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstablecimientosConCoincidenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string crrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string digito_verificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_renovacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string matriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string matricula_estField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string municipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tpcmField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstablecimientosConCoincidencia {
            get {
                return this.EstablecimientosConCoincidenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstablecimientosConCoincidenciaField, value) != true)) {
                    this.EstablecimientosConCoincidenciaField = value;
                    this.RaisePropertyChanged("EstablecimientosConCoincidencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdenField, value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecordId {
            get {
                return this.RecordIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordIdField, value) != true)) {
                    this.RecordIdField = value;
                    this.RaisePropertyChanged("RecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string activo {
            get {
                return this.activoField;
            }
            set {
                if ((object.ReferenceEquals(this.activoField, value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string crr {
            get {
                return this.crrField;
            }
            set {
                if ((object.ReferenceEquals(this.crrField, value) != true)) {
                    this.crrField = value;
                    this.RaisePropertyChanged("crr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string detalle {
            get {
                return this.detalleField;
            }
            set {
                if ((object.ReferenceEquals(this.detalleField, value) != true)) {
                    this.detalleField = value;
                    this.RaisePropertyChanged("detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string digito_verificacion {
            get {
                return this.digito_verificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.digito_verificacionField, value) != true)) {
                    this.digito_verificacionField = value;
                    this.RaisePropertyChanged("digito_verificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha_renovacion {
            get {
                return this.fecha_renovacionField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_renovacionField, value) != true)) {
                    this.fecha_renovacionField = value;
                    this.RaisePropertyChanged("fecha_renovacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula {
            get {
                return this.matriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.matriculaField, value) != true)) {
                    this.matriculaField = value;
                    this.RaisePropertyChanged("matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula_est {
            get {
                return this.matricula_estField;
            }
            set {
                if ((object.ReferenceEquals(this.matricula_estField, value) != true)) {
                    this.matricula_estField = value;
                    this.RaisePropertyChanged("matricula_est");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                if ((object.ReferenceEquals(this.municipioField, value) != true)) {
                    this.municipioField = value;
                    this.RaisePropertyChanged("municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nit {
            get {
                return this.nitField;
            }
            set {
                if ((object.ReferenceEquals(this.nitField, value) != true)) {
                    this.nitField = value;
                    this.RaisePropertyChanged("nit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpcm {
            get {
                return this.tpcmField;
            }
            set {
                if ((object.ReferenceEquals(this.tpcmField, value) != true)) {
                    this.tpcmField = value;
                    this.RaisePropertyChanged("tpcm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeticionDetalle", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class PeticionDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TpcmField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tpcm {
            get {
                return this.TpcmField;
            }
            set {
                if ((object.ReferenceEquals(this.TpcmField, value) != true)) {
                    this.TpcmField = value;
                    this.RaisePropertyChanged("Tpcm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaDetalle", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class RespuestaDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPCamaraComercio.WCFCamaraComercio.ResponseDetalle responseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPCamaraComercio.WCFCamaraComercio.ResponseDetalle response {
            get {
                return this.responseField;
            }
            set {
                if ((object.ReferenceEquals(this.responseField, value) != true)) {
                    this.responseField = value;
                    this.RaisePropertyChanged("response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDetalle", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class ResponseDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPCamaraComercio.WCFCamaraComercio.TiposCertificado[] TiposCertificadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPCamaraComercio.WCFCamaraComercio.ResultadoDetalle[] resultadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPCamaraComercio.WCFCamaraComercio.TiposCertificado[] TiposCertificados {
            get {
                return this.TiposCertificadosField;
            }
            set {
                if ((object.ReferenceEquals(this.TiposCertificadosField, value) != true)) {
                    this.TiposCertificadosField = value;
                    this.RaisePropertyChanged("TiposCertificados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPCamaraComercio.WCFCamaraComercio.ResultadoDetalle[] resultados {
            get {
                return this.resultadosField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadosField, value) != true)) {
                    this.resultadosField = value;
                    this.RaisePropertyChanged("resultados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TiposCertificado", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class TiposCertificado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionCertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorCertificadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionCertificado {
            get {
                return this.DescripcionCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionCertificadoField, value) != true)) {
                    this.DescripcionCertificadoField = value;
                    this.RaisePropertyChanged("DescripcionCertificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCertificado {
            get {
                return this.IdCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCertificadoField, value) != true)) {
                    this.IdCertificadoField = value;
                    this.RaisePropertyChanged("IdCertificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCertificado {
            get {
                return this.NombreCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCertificadoField, value) != true)) {
                    this.NombreCertificadoField = value;
                    this.RaisePropertyChanged("NombreCertificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorCertificado {
            get {
                return this.ValorCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorCertificadoField, value) != true)) {
                    this.ValorCertificadoField = value;
                    this.RaisePropertyChanged("ValorCertificado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoDetalle", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class ResultadoDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Desc_CicmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fec_InicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Mpio_Come_NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tpcm_DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UltRenvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPCamaraComercio.WCFCamaraComercio.CertificadoDetalle[] certificadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string come_NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string come_siglaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dir_comeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPCamaraComercio.WCFCamaraComercio.Establecimiento[] establecimientosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroestablecimientosactivosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivoField, value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc_Cicm {
            get {
                return this.Desc_CicmField;
            }
            set {
                if ((object.ReferenceEquals(this.Desc_CicmField, value) != true)) {
                    this.Desc_CicmField = value;
                    this.RaisePropertyChanged("Desc_Cicm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fec_Inicio {
            get {
                return this.Fec_InicioField;
            }
            set {
                if ((object.ReferenceEquals(this.Fec_InicioField, value) != true)) {
                    this.Fec_InicioField = value;
                    this.RaisePropertyChanged("Fec_Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mpio_Come_Nom {
            get {
                return this.Mpio_Come_NomField;
            }
            set {
                if ((object.ReferenceEquals(this.Mpio_Come_NomField, value) != true)) {
                    this.Mpio_Come_NomField = value;
                    this.RaisePropertyChanged("Mpio_Come_Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tpcm_Desc {
            get {
                return this.Tpcm_DescField;
            }
            set {
                if ((object.ReferenceEquals(this.Tpcm_DescField, value) != true)) {
                    this.Tpcm_DescField = value;
                    this.RaisePropertyChanged("Tpcm_Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UltRenv {
            get {
                return this.UltRenvField;
            }
            set {
                if ((object.ReferenceEquals(this.UltRenvField, value) != true)) {
                    this.UltRenvField = value;
                    this.RaisePropertyChanged("UltRenv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPCamaraComercio.WCFCamaraComercio.CertificadoDetalle[] certificados {
            get {
                return this.certificadosField;
            }
            set {
                if ((object.ReferenceEquals(this.certificadosField, value) != true)) {
                    this.certificadosField = value;
                    this.RaisePropertyChanged("certificados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string come_Nom {
            get {
                return this.come_NomField;
            }
            set {
                if ((object.ReferenceEquals(this.come_NomField, value) != true)) {
                    this.come_NomField = value;
                    this.RaisePropertyChanged("come_Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string come_sigla {
            get {
                return this.come_siglaField;
            }
            set {
                if ((object.ReferenceEquals(this.come_siglaField, value) != true)) {
                    this.come_siglaField = value;
                    this.RaisePropertyChanged("come_sigla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dir_come {
            get {
                return this.dir_comeField;
            }
            set {
                if ((object.ReferenceEquals(this.dir_comeField, value) != true)) {
                    this.dir_comeField = value;
                    this.RaisePropertyChanged("dir_come");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPCamaraComercio.WCFCamaraComercio.Establecimiento[] establecimientos {
            get {
                return this.establecimientosField;
            }
            set {
                if ((object.ReferenceEquals(this.establecimientosField, value) != true)) {
                    this.establecimientosField = value;
                    this.RaisePropertyChanged("establecimientos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identificacion {
            get {
                return this.identificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.identificacionField, value) != true)) {
                    this.identificacionField = value;
                    this.RaisePropertyChanged("identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroestablecimientosactivos {
            get {
                return this.numeroestablecimientosactivosField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroestablecimientosactivosField, value) != true)) {
                    this.numeroestablecimientosactivosField = value;
                    this.RaisePropertyChanged("numeroestablecimientosactivos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificadoDetalle", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class CertificadoDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoGeneracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaEstablecimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorCertificadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoGeneracion {
            get {
                return this.CodigoGeneracionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoGeneracionField, value) != true)) {
                    this.CodigoGeneracionField = value;
                    this.RaisePropertyChanged("CodigoGeneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCertificado {
            get {
                return this.IdCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCertificadoField, value) != true)) {
                    this.IdCertificadoField = value;
                    this.RaisePropertyChanged("IdCertificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatriculaEstablecimiento {
            get {
                return this.MatriculaEstablecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaEstablecimientoField, value) != true)) {
                    this.MatriculaEstablecimientoField = value;
                    this.RaisePropertyChanged("MatriculaEstablecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCertificado {
            get {
                return this.NombreCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCertificadoField, value) != true)) {
                    this.NombreCertificadoField = value;
                    this.RaisePropertyChanged("NombreCertificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorCertificado {
            get {
                return this.ValorCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorCertificadoField, value) != true)) {
                    this.ValorCertificadoField = value;
                    this.RaisePropertyChanged("ValorCertificado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Establecimiento", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class Establecimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPCamaraComercio.WCFCamaraComercio.CertificadosEstablecimiento[] CertificadosEstablecimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionEstablecimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoEstablecimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaEstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioEstablecimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEstablecimientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPCamaraComercio.WCFCamaraComercio.CertificadosEstablecimiento[] CertificadosEstablecimiento {
            get {
                return this.CertificadosEstablecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificadosEstablecimientoField, value) != true)) {
                    this.CertificadosEstablecimientoField = value;
                    this.RaisePropertyChanged("CertificadosEstablecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionEstablecimiento {
            get {
                return this.DireccionEstablecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionEstablecimientoField, value) != true)) {
                    this.DireccionEstablecimientoField = value;
                    this.RaisePropertyChanged("DireccionEstablecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoEstablecimiento {
            get {
                return this.EstadoEstablecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoEstablecimientoField, value) != true)) {
                    this.EstadoEstablecimientoField = value;
                    this.RaisePropertyChanged("EstadoEstablecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatriculaEst {
            get {
                return this.MatriculaEstField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaEstField, value) != true)) {
                    this.MatriculaEstField = value;
                    this.RaisePropertyChanged("MatriculaEst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MunicipioEstablecimiento {
            get {
                return this.MunicipioEstablecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioEstablecimientoField, value) != true)) {
                    this.MunicipioEstablecimientoField = value;
                    this.RaisePropertyChanged("MunicipioEstablecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEstablecimiento {
            get {
                return this.NombreEstablecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEstablecimientoField, value) != true)) {
                    this.NombreEstablecimientoField = value;
                    this.RaisePropertyChanged("NombreEstablecimiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificadosEstablecimiento", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class CertificadosEstablecimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoGeneracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaEstablecimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorCertificadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoGeneracion {
            get {
                return this.CodigoGeneracionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoGeneracionField, value) != true)) {
                    this.CodigoGeneracionField = value;
                    this.RaisePropertyChanged("CodigoGeneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCertificado {
            get {
                return this.IdCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCertificadoField, value) != true)) {
                    this.IdCertificadoField = value;
                    this.RaisePropertyChanged("IdCertificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatriculaEstablecimiento {
            get {
                return this.MatriculaEstablecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaEstablecimientoField, value) != true)) {
                    this.MatriculaEstablecimientoField = value;
                    this.RaisePropertyChanged("MatriculaEstablecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCertificado {
            get {
                return this.NombreCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCertificadoField, value) != true)) {
                    this.NombreCertificadoField = value;
                    this.RaisePropertyChanged("NombreCertificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorCertificado {
            get {
                return this.ValorCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorCertificadoField, value) != true)) {
                    this.ValorCertificadoField = value;
                    this.RaisePropertyChanged("ValorCertificado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Datos", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class Datos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorizaEnvioEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorizaEnvioSMSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPCamaraComercio.WCFCamaraComercio.Certificado[] CertificadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoDepartamentoCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoMunicipioCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoPaisCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlataformaClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerNombreCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoNombreCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoIdentificacionCompradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorCompraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutorizaEnvioEmail {
            get {
                return this.AutorizaEnvioEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorizaEnvioEmailField, value) != true)) {
                    this.AutorizaEnvioEmailField = value;
                    this.RaisePropertyChanged("AutorizaEnvioEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutorizaEnvioSMS {
            get {
                return this.AutorizaEnvioSMSField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorizaEnvioSMSField, value) != true)) {
                    this.AutorizaEnvioSMSField = value;
                    this.RaisePropertyChanged("AutorizaEnvioSMS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPCamaraComercio.WCFCamaraComercio.Certificado[] Certificados {
            get {
                return this.CertificadosField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificadosField, value) != true)) {
                    this.CertificadosField = value;
                    this.RaisePropertyChanged("Certificados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoDepartamentoComprador {
            get {
                return this.CodigoDepartamentoCompradorField;
            }
            set {
                if ((this.CodigoDepartamentoCompradorField.Equals(value) != true)) {
                    this.CodigoDepartamentoCompradorField = value;
                    this.RaisePropertyChanged("CodigoDepartamentoComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoMunicipioComprador {
            get {
                return this.CodigoMunicipioCompradorField;
            }
            set {
                if ((this.CodigoMunicipioCompradorField.Equals(value) != true)) {
                    this.CodigoMunicipioCompradorField = value;
                    this.RaisePropertyChanged("CodigoMunicipioComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPaisComprador {
            get {
                return this.CodigoPaisCompradorField;
            }
            set {
                if ((this.CodigoPaisCompradorField.Equals(value) != true)) {
                    this.CodigoPaisCompradorField = value;
                    this.RaisePropertyChanged("CodigoPaisComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionComprador {
            get {
                return this.DireccionCompradorField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionCompradorField, value) != true)) {
                    this.DireccionCompradorField = value;
                    this.RaisePropertyChanged("DireccionComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailComprador {
            get {
                return this.EmailCompradorField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailCompradorField, value) != true)) {
                    this.EmailCompradorField = value;
                    this.RaisePropertyChanged("EmailComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificacionComprador {
            get {
                return this.IdentificacionCompradorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionCompradorField, value) != true)) {
                    this.IdentificacionCompradorField = value;
                    this.RaisePropertyChanged("IdentificacionComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MunicipioComprador {
            get {
                return this.MunicipioCompradorField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioCompradorField, value) != true)) {
                    this.MunicipioCompradorField = value;
                    this.RaisePropertyChanged("MunicipioComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComprador {
            get {
                return this.NombreCompradorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompradorField, value) != true)) {
                    this.NombreCompradorField = value;
                    this.RaisePropertyChanged("NombreComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlataformaCliente {
            get {
                return this.PlataformaClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.PlataformaClienteField, value) != true)) {
                    this.PlataformaClienteField = value;
                    this.RaisePropertyChanged("PlataformaCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellidoComprador {
            get {
                return this.PrimerApellidoCompradorField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoCompradorField, value) != true)) {
                    this.PrimerApellidoCompradorField = value;
                    this.RaisePropertyChanged("PrimerApellidoComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerNombreComprador {
            get {
                return this.PrimerNombreCompradorField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerNombreCompradorField, value) != true)) {
                    this.PrimerNombreCompradorField = value;
                    this.RaisePropertyChanged("PrimerNombreComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenciaPago {
            get {
                return this.ReferenciaPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaPagoField, value) != true)) {
                    this.ReferenciaPagoField = value;
                    this.RaisePropertyChanged("ReferenciaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellidoComprador {
            get {
                return this.SegundoApellidoCompradorField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoCompradorField, value) != true)) {
                    this.SegundoApellidoCompradorField = value;
                    this.RaisePropertyChanged("SegundoApellidoComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoNombreComprador {
            get {
                return this.SegundoNombreCompradorField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoNombreCompradorField, value) != true)) {
                    this.SegundoNombreCompradorField = value;
                    this.RaisePropertyChanged("SegundoNombreComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoComprador {
            get {
                return this.TelefonoCompradorField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoCompradorField, value) != true)) {
                    this.TelefonoCompradorField = value;
                    this.RaisePropertyChanged("TelefonoComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoComprador {
            get {
                return this.TipoCompradorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCompradorField, value) != true)) {
                    this.TipoCompradorField = value;
                    this.RaisePropertyChanged("TipoComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoIdentificacionComprador {
            get {
                return this.TipoIdentificacionCompradorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoIdentificacionCompradorField, value) != true)) {
                    this.TipoIdentificacionCompradorField = value;
                    this.RaisePropertyChanged("TipoIdentificacionComprador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCompra {
            get {
                return this.ValorCompraField;
            }
            set {
                if ((this.ValorCompraField.Equals(value) != true)) {
                    this.ValorCompraField = value;
                    this.RaisePropertyChanged("ValorCompra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Certificado", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class Certificado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoGeneracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaEstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCertificadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string matriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tpcmField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoGeneracion {
            get {
                return this.CodigoGeneracionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoGeneracionField, value) != true)) {
                    this.CodigoGeneracionField = value;
                    this.RaisePropertyChanged("CodigoGeneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCertificado {
            get {
                return this.IdCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCertificadoField, value) != true)) {
                    this.IdCertificadoField = value;
                    this.RaisePropertyChanged("IdCertificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatriculaEst {
            get {
                return this.MatriculaEstField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaEstField, value) != true)) {
                    this.MatriculaEstField = value;
                    this.RaisePropertyChanged("MatriculaEst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCertificados {
            get {
                return this.NumeroCertificadosField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCertificadosField, value) != true)) {
                    this.NumeroCertificadosField = value;
                    this.RaisePropertyChanged("NumeroCertificados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula {
            get {
                return this.matriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.matriculaField, value) != true)) {
                    this.matriculaField = value;
                    this.RaisePropertyChanged("matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpcm {
            get {
                return this.tpcmField;
            }
            set {
                if ((object.ReferenceEquals(this.tpcmField, value) != true)) {
                    this.tpcmField = value;
                    this.RaisePropertyChanged("tpcm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLSDatosCertificado", Namespace="http://schemas.datacontract.org/2004/07/WCFCamaraComercio.Clases")]
    [System.SerializableAttribute()]
    public partial class CLSDatosCertificado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string copiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idcompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string matriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string matriculaestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referenciaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tpcmField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCertificado {
            get {
                return this.IdCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCertificadoField, value) != true)) {
                    this.IdCertificadoField = value;
                    this.RaisePropertyChanged("IdCertificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string copia {
            get {
                return this.copiaField;
            }
            set {
                if ((object.ReferenceEquals(this.copiaField, value) != true)) {
                    this.copiaField = value;
                    this.RaisePropertyChanged("copia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idcompra {
            get {
                return this.idcompraField;
            }
            set {
                if ((object.ReferenceEquals(this.idcompraField, value) != true)) {
                    this.idcompraField = value;
                    this.RaisePropertyChanged("idcompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula {
            get {
                return this.matriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.matriculaField, value) != true)) {
                    this.matriculaField = value;
                    this.RaisePropertyChanged("matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matriculaest {
            get {
                return this.matriculaestField;
            }
            set {
                if ((object.ReferenceEquals(this.matriculaestField, value) != true)) {
                    this.matriculaestField = value;
                    this.RaisePropertyChanged("matriculaest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string referenciaPago {
            get {
                return this.referenciaPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.referenciaPagoField, value) != true)) {
                    this.referenciaPagoField = value;
                    this.RaisePropertyChanged("referenciaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tpcm {
            get {
                return this.tpcmField;
            }
            set {
                if ((object.ReferenceEquals(this.tpcmField, value) != true)) {
                    this.tpcmField = value;
                    this.RaisePropertyChanged("tpcm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFCamaraComercio.IWCFCamaraComercio")]
    public interface IWCFCamaraComercio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/GetGeneralInformation", ReplyAction="http://tempuri.org/IWCFCamaraComercio/GetGeneralInformationResponse")]
        WPCamaraComercio.WCFCamaraComercio.RespuestaConsulta GetGeneralInformation(string paramConsulta, WPCamaraComercio.WCFCamaraComercio.tipo_busqueda tipo_Busqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/GetGeneralInformation", ReplyAction="http://tempuri.org/IWCFCamaraComercio/GetGeneralInformationResponse")]
        System.Threading.Tasks.Task<WPCamaraComercio.WCFCamaraComercio.RespuestaConsulta> GetGeneralInformationAsync(string paramConsulta, WPCamaraComercio.WCFCamaraComercio.tipo_busqueda tipo_Busqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/GetDetalleComerciante", ReplyAction="http://tempuri.org/IWCFCamaraComercio/GetDetalleComercianteResponse")]
        WPCamaraComercio.WCFCamaraComercio.RespuestaDetalle GetDetalleComerciante(WPCamaraComercio.WCFCamaraComercio.PeticionDetalle paramConsulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/GetDetalleComerciante", ReplyAction="http://tempuri.org/IWCFCamaraComercio/GetDetalleComercianteResponse")]
        System.Threading.Tasks.Task<WPCamaraComercio.WCFCamaraComercio.RespuestaDetalle> GetDetalleComercianteAsync(WPCamaraComercio.WCFCamaraComercio.PeticionDetalle paramConsulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/SendPayInformation", ReplyAction="http://tempuri.org/IWCFCamaraComercio/SendPayInformationResponse")]
        System.Collections.Generic.Dictionary<string, string> SendPayInformation(WPCamaraComercio.WCFCamaraComercio.Datos payInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/SendPayInformation", ReplyAction="http://tempuri.org/IWCFCamaraComercio/SendPayInformationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> SendPayInformationAsync(WPCamaraComercio.WCFCamaraComercio.Datos payInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/GetPayReference", ReplyAction="http://tempuri.org/IWCFCamaraComercio/GetPayReferenceResponse")]
        string GetPayReference();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/GetPayReference", ReplyAction="http://tempuri.org/IWCFCamaraComercio/GetPayReferenceResponse")]
        System.Threading.Tasks.Task<string> GetPayReferenceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/UpdatePrintedCopy", ReplyAction="http://tempuri.org/IWCFCamaraComercio/UpdatePrintedCopyResponse")]
        int UpdatePrintedCopy(int idTransaccion, int idCertificado, string matricula, string matriculaEst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/UpdatePrintedCopy", ReplyAction="http://tempuri.org/IWCFCamaraComercio/UpdatePrintedCopyResponse")]
        System.Threading.Tasks.Task<int> UpdatePrintedCopyAsync(int idTransaccion, int idCertificado, string matricula, string matriculaEst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/InsertError", ReplyAction="http://tempuri.org/IWCFCamaraComercio/InsertErrorResponse")]
        void InsertError(string corresponsal, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/InsertError", ReplyAction="http://tempuri.org/IWCFCamaraComercio/InsertErrorResponse")]
        System.Threading.Tasks.Task InsertErrorAsync(string corresponsal, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/GetCertified", ReplyAction="http://tempuri.org/IWCFCamaraComercio/GetCertifiedResponse")]
        byte[] GetCertified(WPCamaraComercio.WCFCamaraComercio.CLSDatosCertificado datosCertificado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/GetCertified", ReplyAction="http://tempuri.org/IWCFCamaraComercio/GetCertifiedResponse")]
        System.Threading.Tasks.Task<byte[]> GetCertifiedAsync(WPCamaraComercio.WCFCamaraComercio.CLSDatosCertificado datosCertificado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/GetCertifiedString", ReplyAction="http://tempuri.org/IWCFCamaraComercio/GetCertifiedStringResponse")]
        string GetCertifiedString(WPCamaraComercio.WCFCamaraComercio.CLSDatosCertificado datosCertificado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCamaraComercio/GetCertifiedString", ReplyAction="http://tempuri.org/IWCFCamaraComercio/GetCertifiedStringResponse")]
        System.Threading.Tasks.Task<string> GetCertifiedStringAsync(WPCamaraComercio.WCFCamaraComercio.CLSDatosCertificado datosCertificado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFCamaraComercioChannel : WPCamaraComercio.WCFCamaraComercio.IWCFCamaraComercio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFCamaraComercioClient : System.ServiceModel.ClientBase<WPCamaraComercio.WCFCamaraComercio.IWCFCamaraComercio>, WPCamaraComercio.WCFCamaraComercio.IWCFCamaraComercio {
        
        public WCFCamaraComercioClient() {
        }
        
        public WCFCamaraComercioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFCamaraComercioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCamaraComercioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCamaraComercioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WPCamaraComercio.WCFCamaraComercio.RespuestaConsulta GetGeneralInformation(string paramConsulta, WPCamaraComercio.WCFCamaraComercio.tipo_busqueda tipo_Busqueda) {
            return base.Channel.GetGeneralInformation(paramConsulta, tipo_Busqueda);
        }
        
        public System.Threading.Tasks.Task<WPCamaraComercio.WCFCamaraComercio.RespuestaConsulta> GetGeneralInformationAsync(string paramConsulta, WPCamaraComercio.WCFCamaraComercio.tipo_busqueda tipo_Busqueda) {
            return base.Channel.GetGeneralInformationAsync(paramConsulta, tipo_Busqueda);
        }
        
        public WPCamaraComercio.WCFCamaraComercio.RespuestaDetalle GetDetalleComerciante(WPCamaraComercio.WCFCamaraComercio.PeticionDetalle paramConsulta) {
            return base.Channel.GetDetalleComerciante(paramConsulta);
        }
        
        public System.Threading.Tasks.Task<WPCamaraComercio.WCFCamaraComercio.RespuestaDetalle> GetDetalleComercianteAsync(WPCamaraComercio.WCFCamaraComercio.PeticionDetalle paramConsulta) {
            return base.Channel.GetDetalleComercianteAsync(paramConsulta);
        }
        
        public System.Collections.Generic.Dictionary<string, string> SendPayInformation(WPCamaraComercio.WCFCamaraComercio.Datos payInformation) {
            return base.Channel.SendPayInformation(payInformation);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> SendPayInformationAsync(WPCamaraComercio.WCFCamaraComercio.Datos payInformation) {
            return base.Channel.SendPayInformationAsync(payInformation);
        }
        
        public string GetPayReference() {
            return base.Channel.GetPayReference();
        }
        
        public System.Threading.Tasks.Task<string> GetPayReferenceAsync() {
            return base.Channel.GetPayReferenceAsync();
        }
        
        public int UpdatePrintedCopy(int idTransaccion, int idCertificado, string matricula, string matriculaEst) {
            return base.Channel.UpdatePrintedCopy(idTransaccion, idCertificado, matricula, matriculaEst);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePrintedCopyAsync(int idTransaccion, int idCertificado, string matricula, string matriculaEst) {
            return base.Channel.UpdatePrintedCopyAsync(idTransaccion, idCertificado, matricula, matriculaEst);
        }
        
        public void InsertError(string corresponsal, string mensaje) {
            base.Channel.InsertError(corresponsal, mensaje);
        }
        
        public System.Threading.Tasks.Task InsertErrorAsync(string corresponsal, string mensaje) {
            return base.Channel.InsertErrorAsync(corresponsal, mensaje);
        }
        
        public byte[] GetCertified(WPCamaraComercio.WCFCamaraComercio.CLSDatosCertificado datosCertificado) {
            return base.Channel.GetCertified(datosCertificado);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetCertifiedAsync(WPCamaraComercio.WCFCamaraComercio.CLSDatosCertificado datosCertificado) {
            return base.Channel.GetCertifiedAsync(datosCertificado);
        }
        
        public string GetCertifiedString(WPCamaraComercio.WCFCamaraComercio.CLSDatosCertificado datosCertificado) {
            return base.Channel.GetCertifiedString(datosCertificado);
        }
        
        public System.Threading.Tasks.Task<string> GetCertifiedStringAsync(WPCamaraComercio.WCFCamaraComercio.CLSDatosCertificado datosCertificado) {
            return base.Channel.GetCertifiedStringAsync(datosCertificado);
        }
    }
}
